competitors/urls.py
from django.urls import path

from . import views

from .model import _class, event

app_name = 'competitors'
urlpatterns = [
    path('', views.index, name='index'),
    path('run/', views.run, name='run'),
    path('results/', views.results, name='results'),
    path('setup/', views.setup, name='setup'),

    path('run/send_ready/', views.send_ready, name='send_ready'),
    path('run/competitor/', views.save_competitor, name='save_competitor'),
    path('run/save_result/', views.save_result, name='save_result'),
    path('run/reset/', views.reset, name='reset'),
    path('run/send_msg_to_screen/', views.send_msg_to_screen, name='send_msg_to_screen'),

    path('classes/', _class.index, name='classes'),
    path('classes/delete/<int:id>/', _class.delete, name="delete_class"),
    path('classes/update/<name>/', _class.update, name="update_class"),

    path('events/', event.index, name='events'),
    path('events/delete/<int:id>/', event.delete, name="delete_event"),
    path('events/<int:id>/', event.set_current_event, name="set_current_event"),
    # path('results/export/', views.export_results, name='export_results'),
]

tractor_pull/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('competitors/', include('competitors.urls')),
    path('admin/', admin.site.urls),
]

competitors/models.py
from django.db import models


class Event(models.Model):
    event_name = models.CharField(max_length=50, unique=True)
    status = models.BooleanField(default=False)


class Class(models.Model):
    class_name = models.CharField(max_length=50, unique=True)
    pull_factor = models.IntegerField(default=85)


class Competitor(models.Model):
    competitor_no = models.IntegerField()
    competitor_name = models.CharField(max_length=50)
    tractor_name = models.CharField(max_length=50, null=True)
    weight = models.IntegerField()
    clasS = models.ForeignKey(Class, on_delete=models.CASCADE)
    pull_factor = models.IntegerField(default=85)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)


class Result(models.Model):
    competitor = models.ForeignKey(Competitor, on_delete=models.CASCADE)
    weight = models.IntegerField(default=0)
    pull_factor = models.IntegerField() ###
    distance = models.FloatField()
    run_date = models.DateField('date run')
    run_time = models.TimeField('time run')
    event_name = models.CharField(max_length=50)

competitors/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt

from competitors.tasks import send_ready_task, send_msg_to_screen_task

from .models import Class, Event, Competitor, Result

from datetime import date, datetime
import time

import glob
import serial

import csv
from django.http import HttpResponse

# below library is for the export option in competitors/result
import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
# ----------------end -------------------------------------


# uri: 'competitors/
# action: redirect to 'competitors/run'
def index(request):
  return redirect('competitors:run')

# Export to csv and pdf commented out to allow for the 
# initial download options to work
# REMEMBER TO UNCOMMENT PATH IN URLS.PY
# def export_results(request):
#     event_id = request.GET.get('event_id')
#     export_format = request.GET.get('format', 'csv')
    
#     if event_id:
#         event = Event.objects.get(id=event_id)
#         results = Result.objects.filter(event_name=event.event_name)
#     else:
#         return HttpResponse("No event selected", status=400)
    
#     if export_format == 'pdf':
#         response = HttpResponse(content_type='application/pdf')
#         response['Content-Disposition'] = f'attachment; filename="results_{event.event_name}.pdf"'
        
#         buffer = io.BytesIO()
#         doc = SimpleDocTemplate(buffer, pagesize=letter, title=f"Competition Results - {event.event_name}")
#         elements = []
#         styles = getSampleStyleSheet()
        
#         title = Paragraph(f"<b>Competition Results - {event.event_name}</b>", styles['Title'])
#         elements.append(title)
#         elements.append(Spacer(1, 12))
        
#         data = [['#', 'Competitor No', 'Name', 'Weight', 'Distance', 'Date', 'Time', 'Pull Factor']]
        
#         for idx, result in enumerate(results, start=1):
#             data.append([
#                 str(idx),
#                 str(result.competitor.competitor_no),
#                 result.competitor.competitor_name,
#                 str(result.weight),
#                 str(result.distance),
#                 str(result.run_date),
#                 str(result.run_time),
#                 str(result.pull_factor)
#             ])
        
#         table = Table(data, repeatRows=1)
#         table.setStyle(TableStyle([
#             ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
#             ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
#             ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
#             ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
#             ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
#             ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
#             ('GRID', (0, 0), (-1, -1), 1, colors.black)
#         ]))
        
#         elements.append(table)
#         doc.build(elements)
#         buffer.seek(0)
#         response.write(buffer.read())
#         return response
    
#     # Default to CSV export
#     response = HttpResponse(content_type='text/csv')
#     response['Content-Disposition'] = f'attachment; filename="results_{event.event_name}.csv"'
    
#     writer = csv.writer(response)
#     writer.writerow(['#', 'Competitor No', 'Name', 'Weight', 'Distance', 'Date', 'Time', 'Pull Factor'])
    
#     for idx, result in enumerate(results, start=1):
#         writer.writerow([
#             idx,
#             result.competitor.competitor_no,
#             result.competitor.competitor_name,
#             result.weight,
#             result.distance,
#             result.run_date,
#             result.run_time,
#             result.pull_factor
#         ])
    
#     return response


# uri: 'competitors/run'
# action: show run page with data of class, competitor, result
def run(request):
  port = '/dev/ttyUSB0'

  result = None
  try:
    s = serial.Serial(port)
    s.close()
    result = port
  except (OSError, serial.SerialException):
    pass

  connection = 'Disconnected'
  if result:
    connection = 'Connected'

  classes = Class.objects.all()
  try:
    current_event = Event.objects.get(status=True)
  except Event.DoesNotExist:
    # Use the first event on the list as the default if the current event is not available
    current_event = Event.objects.first()
  results = Result.objects.filter(event_name=current_event.event_name).all()
  #results = Result.objects.filter(event_name=Event.objects.get(status=True).event_name).all()
  #current_event = Event.objects.get(status=True)
  competitors = Competitor.objects.filter(event=current_event).all()

  for competitor in competitors:
    competitor.clasS.id -= Class.objects.first().id

  return render(request, 'components/run.html', {
    'classes': classes,
    'current_event': current_event,
    'results': results,
    'competitors': competitors,
    'connection': connection
  })

# uri: 'competitors/results'
# action: show the competition results
def results(request):
    event_name = request.GET.get("event_name")  # Get event name from URL query params          
    results = Result.objects.all()
    
    if event_name:
        results = results.filter(competitor__result__event_name=event_name).distinct()  
    
    events = Event.objects.all().values("id", "event_name").distinct()
    current_event = Event.objects.filter(status=True).first()    

    return render(request, "components/results.html", {
        "results": results,
        "current_event": current_event,
        "events": events,
        "selected_event": event_name  # Pass selected event back to the template
    })


# uri: 'competitors/setup'
# action: edit class and event
def setup(request):
  classes = Class.objects.all()
  events = Event.objects.all()
  #current_event = Event.objects.get(status=True)
  try:
    current_event = Event.objects.get(status=True)
  except Event.DoesNotExist:
    # Use the first event on the list as the default if the current event is not available
    current_event = Event.objects.first()

  return render(request, 'components/setup.html', {
    'classes': classes,
    'events': events,
    'current_event': current_event
  })

# uri: 'competitors/send_ready'
# action: send ready msg to rs232
@csrf_exempt
def send_ready(request):
  pull_factor = request.POST.get('pull_factor')
  weight = request.POST.get('weight')
  global current_task
  current_task = send_ready_task.delay(pull_factor, weight)
  return HttpResponse('success')

@csrf_exempt
def reset(request):
  global current_task
  current_task.revoke(terminate=True)
  return HttpResponse('success')

@csrf_exempt
def send_msg_to_screen(request):
  send_msg_to_screen_task.delay(request.POST.get('msg'))
  return HttpResponse('success')

# @csrf_exempt
# def save_competitor(request):
#   no = request.POST.get('competitor_no')
#   if Competitor.objects.filter(competitor_no=no, event=Event.objects.get(status=True)):
#     competitor = Competitor.objects.get(competitor_no=no, event=Event.objects.get(status=True))
#   else:
#     competitor = Competitor()
#   competitor.competitor_no = request.POST.get('competitor_no')
#   competitor.competitor_name = request.POST.get('competitor_name')
#   competitor.tractor_name = request.POST.get('tractor_name')
#   competitor.weight = request.POST.get('competitor_weight')
#   competitor.clasS = Class.objects.get(class_name=request.POST.get('clasS'))
#   competitor.pull_factor = request.POST.get('pull_factor')
#   competitor.event = Event.objects.get(status=True)
#   competitor.save()

#   c = Class.objects.get(class_name=request.POST.get('clasS'))
#   if not c.pull_factor == competitor.pull_factor:
#     c.pull_factor = competitor.pull_factor
#     c.save()

#   return HttpResponse('success!')

@csrf_exempt
def save_competitor(request):
    no = request.POST.get('competitor_no')
    current_event = Event.objects.get(status=True)
    
    # Fetch class object
    try:
        selected_class = Class.objects.get(class_name=request.POST.get('clasS'))
    except Class.DoesNotExist:
        return HttpResponse("Error: Selected class does not exist.", status=400)

    # Ensure pull_factor is set
    pull_factor = request.POST.get('pull_factor')
    if not pull_factor:  # If not provided, fetch from the class
        pull_factor = selected_class.pull_factor

    competitor, created = Competitor.objects.get_or_create(
        competitor_no=no,
        event=current_event,
        defaults={
            'competitor_name': request.POST.get('competitor_name'),
            'tractor_name': request.POST.get('tractor_name'),
            'weight': request.POST.get('competitor_weight'),
            'clasS': Class.objects.get(class_name=request.POST.get('clasS')),
            'pull_factor': pull_factor
        }
    )
    
    if not created:
        # Update only if the class is changed
        if competitor.clasS.class_name != request.POST.get('clasS'):
            competitor.clasS = Class.objects.get(class_name=request.POST.get('clasS'))
        
        # Update pull factor only if it has changed
        if competitor.pull_factor != request.POST.get('pull_factor'):
            competitor.pull_factor = request.POST.get('pull_factor')
        
        competitor.save()

    return HttpResponse('success!')
  

@csrf_exempt
def save_result(request):
  competitor_no = request.POST.get('competitor_no')
  weight = request.POST.get('weight')
  pull_factor = request.POST.get('pull_factor')
  distance = request.POST.get('distance')
  competitor = Competitor.objects.get(competitor_no=competitor_no, event=Event.objects.get(status=True))
  #t = time.localtime()
  #  current_time = time.strftime("%H:%M:%S", t)
  t = datetime.now()
  current_time = t.strftime("%H:%M:%S")

  
  result = Result(
    competitor = competitor,

competitors/templates/components/results.html
{% extends 'layout/base.html' %}
{% load static %}

{% block nav_bar %}
  <!-- BEGIN Nav -->
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a href="{% url 'competitors:index' %}" class="nav-link">Run</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'competitors:results' %}" class="nav-link active">Results</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'competitors:setup' %}" class="nav-link">Setup</a>
    </li>
  </ul>
  <!-- END Nav -->
{% endblock %}

{% block nav_bar_wrap %}
  <!-- BEGIN Nav -->
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a href="{% url 'competitors:index' %}" class="nav-link">Run</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'competitors:results' %}" class="nav-link active">Results</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'competitors:setup' %}" class="nav-link">Setup</a>
    </li>
  </ul>
  <!-- END Nav -->
{% endblock %}

{% block content %}
<div class="container-fluid">
  <!-- export result -->
    <div class="card p-3">
      <h5 class="mb-3">Export Competition Results</h5>
      <form id="resultsForm" action="{% url 'competitors:results' %}" method="GET">
        <input type="hidden" name="export" id="exportField" value="0">
        <div class="row">
          <div class="col-4">
            <label for="event_id">Select Event:</label>
            <select name="event_name" id="event_name" class="form-control" onchange="this.form.submit()">
              <option value="" selected>-- All Events --</option>
              {% for event in events %}
                  <option value="{{ event.event_name }}" {% if event.event_name == selected_event %}selected{% endif %}>
                      {{ event.event_name }}
                  </option>
              {% endfor %}
            </select>
          </div>
      
          {% comment %} <div class="col-4"> 
              <label for="format">Select Format:</label>
              <select name="format" id="format" class="form-control">
                <option value="pdf">PDF</option>
                <option value="csv">CSV/Excel</option>
              </select>
            </div>
        
            <div class="col-4 d-flex align-items-end">
              <button type="submit" class="btn btn-success w-100" onclick="alert("yes")">
                Download
              </button>
            </div>
          {% endcomment %}
        </div>
      </form>
      
</div>
  
      <br>

  <div class="portlet">
    <div class="portlet-header portlet-header-bordered">
      <h3 class="portlet-title">Competition Results</h3>
    </div>
    <div class="portlet-body">
      <!-- BEGIN Table -->
      <div class="portlet-body">
        <!-- BEGIN Datatable -->
        <table id="datatable-1" class="table table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Competitior Name</th>
                    <th>Event Name</th>
                    <th>Pull Factor</th>
                    <th>Weight</th>
                    <th>Distance</th>
                    <th>Date</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
              {% if results %}
                {% for result in results %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ result.competitor.competitor_name }}</td>
                    <td>{{ result.event_name }}</td>
                    <td>{{ result.pull_factor }}</td>
                    <td>{{ result.weight }}</td>
                    <td>{{ result.distance }}</td>
                    <td>{{ result.run_date }}</td>
                    <td>{{ result.run_time }}</td>
                  </tr>
                {% endfor %}
              {% else %}
                <tr>
                  <td colspan="8" class="text-center">No results found for this event.</td>
                </tr>
              {% endif %}
            </tbody>
            
        </table>
        <!-- END Datatable -->
      </div>
      <!-- END Table -->
    </div>
  </div>
</div>
{% endblock %}

competitors/templates/components/setup.html
{% extends 'layout/base.html' %}
{% load static %}

{% block nav_bar %}
  <!-- BEGIN Nav -->
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a href="{% url 'competitors:index' %}" class="nav-link">Run</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'competitors:results' %}" class="nav-link">Results</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'competitors:setup' %}" class="nav-link active">Setup</a>
    </li>
  </ul>
  <!-- END Nav -->
{% endblock %}

{% block nav_bar_wrap %}
  <!-- BEGIN Nav -->
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a href="{% url 'competitors:index' %}" class="nav-link">Run</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'competitors:results' %}" class="nav-link">Results</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'competitors:setup' %}" class="nav-link active">Setup</a>
    </li>
  </ul>
  <!-- END Nav -->
{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="portlet">
        <div class="portlet-header portlet-header-bordered">
          <h3 class="portlet-title">Events</h3>
        </div>
        <div class="portlet-body">
          <form action="{% url 'competitors:events' %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <!-- BEGIN Form Group -->
              <div class="form-group col-md-8">
                <!-- BEGIN Float Label -->
                <div class="float-label">
                  <input type="text" id="event_name" name="event_name" class="form-control" placeholder="Add new event">
                  <label for="event_name">New Event</label>
                </div>
                <!-- END Float Label -->
              </div>
              <!-- END Form Group -->
              <!-- BEGIN Form Group -->
              <div class="form-group col-md-4">
                <button class="btn btn-primary" type="submit">Save</button>
              </div>
              <!-- END Form Group -->
            </div>
          </form>
          <!-- BEGIN Table -->
          <table class="table table-bordered table-striped table-hover mb-0" id="event_table">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
              </tr>
            </thead>
            <tbody>
              {% for event in events %}
                <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                  {{ event.event_name }}
                  <span>
                    <a href="{% url 'competitors:delete_event' event.pk %}"><button class="btn btn-danger btn-icon float-right">
                     <i class="fa fa-times"></i>
                    </button></a>
                    {% if event.status == False %}
                    <a href="{% url 'competitors:set_current_event' event.pk %}"><button class="btn btn-info btn-icon float-right mr-2">
                      <i class="fa fa-check"></i>
                    </button></a>
                    {% endif %}
                  </span>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <!-- END Table -->
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="portlet">
        <div class="portlet-header portlet-header-bordered">
          <h3 class="portlet-title">Classes</h3>
        </div>
        <div class="portlet-body">
          <form action="{% url 'competitors:classes' %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
              <!-- BEGIN Form Group -->
              <div class="form-group col-md-5">
                <!-- BEGIN Float Label -->
                <div class="float-label">
                  <input type="text" id="class_name" name="class_name" class="form-control" placeholder="Add new class">
                  <label for="class_name">New Class</label>
                </div>
                <!-- END Float Label -->
              </div>
              <!-- END Form Group -->
              <!-- BEGIN Form Group -->
              <div class="form-group col-md-5">
                <!-- BEGIN Float Label -->
                <div class="float-label">
                  <input type="number" onKeyPress="if(this.value.length==2) return false;" id="pull_factor" name="pull_factor" class="form-control" placeholder="Pull Factor">
                  <label for="pull_factor">Pull Factor</label>
                </div>
                <!-- END Float Label -->
              </div>
              <!-- END Form Group -->
              <!-- BEGIN Form Group -->
              <div class="form-group col-md-2">
                <button class="btn btn-primary" type="submit">Save</button>
              </div>
              <!-- END Form Group -->
            </div>
          </form>
          <!-- BEGIN Table -->
          <table class="table table-bordered table-striped table-hover mb-0">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Pull Factor</th>
              </tr>
            </thead>
            <tbody>
              {% for class in classes %}
                <tr>
                  <th scope="row">{{ forloop.counter }}</th>
                  <td class="class_name">{{ class.class_name }}</td>
                  <td>
                    <input type="number" onKeyPress="if(this.value.length==2) return false;" style="width: 40px; background: transparent; border: none; color: gray;" value="{{class.pull_factor}}" class="pull_factor">
                    <a href="{% url 'competitors:delete_class' class.pk %}"><button class="btn btn-danger btn-icon float-right">
                      <i class="fa fa-times"></i>
                    </button></a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
          <!-- END Table -->
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" src="{% static 'assets/js/setup.js' %}"></script>
{% endblock %}